CREATE TABLE IF NOT EXISTS transaction
(
    id                  UUID,
    changed             Int32,
    created             Int32,
    user                Int32,
    deleted             BOOL,
    hold                Nullable(BOOL),
    income_instrument    Int32,
    income_account       String,
    income              Float64,
    outcome_instrument   Int32,
    outcome_account      String,
    outcome             Float64,
    tag                 Array(UUID),
    merchant            Nullable(UUID),
    payee               String,
    original_payee       String,
    comment             String,
    date                String,
    mcc                 Nullable(Int32),
    reminder_marker      Nullable(UUID),
    op_income            Nullable(Float64),
    op_income_instrument  Nullable(Int32),
    op_outcome           Nullable(Float64),
    op_outcome_instrument Nullable(Int32),
    latitude            Nullable(Float64),
    longitude           Nullable(Float64)
) ENGINE = MergeTree PRIMARY KEY id;