version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - migration

  migration:
    image: migrate/migrate
    env_file: .env
    volumes:
      - ./migration:/migrations
    command: [ "-path=/migrations/", "-database", "clickhouse://localhost:9000?database=zenmoney&username=admin&password=password", "up" ]
    network_mode: host
