services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - migration-clickhouse
      - migration-postgres

  migration-clickhouse:
    image: migrate/migrate
    env_file: .env
    volumes:
      - ./migration:/migrations
    command: [ "-path=/migrations/", "-database", "clickhouse://clickhouse:9000?database=zenmoney&username=admin&password=password", "up" ]
    depends_on:
      - clickhouse

  migration-postgres:
    image: migrate/migrate
    env_file: .env
    volumes:
      - ./migration/postgresql:/migrations
    command: [ "-path=/migrations/", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/zenmoney?sslmode=disable", "up" ]
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
        test: pg_isready -U zenmoney
        interval: 30s
        timeout: 10s
        retries: 3

  clickhouse:
    image: yandex/clickhouse-server
    env_file: .env
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse:/var/lib/clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:8123 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
    postgres:
    clickhouse:
