name: Build and Test
on:
  push:
    branches:
      - feature/*
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lit by go vet
        run: go vet ./...

      - name: Lint by golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: run ./...

      - name: Lint by Staticcheck
        run: go get honnef.co/go/tools/cmd/staticcheck && staticcheck ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: make test-coverage

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: make build