CREATE TABLE IF NOT EXISTS account
(
    id                    UUID,
    changed               Int32,
    user                  Int32,
    role                  Nullable(Int32),
    instrument            Nullable(Int32),
    company               Nullable(Int32),
    type                  String,
    title                 String,
    sync_id                Array(String),
    balance               Nullable(Float64),
    start_balance          Nullable(Float64),
    credit_limit           Nullable(Float64),
    in_balance             UInt8,
    savings               Nullable(BOOL),
    enable_correction      UInt8,
    enable_sms             UInt8,
    archive               UInt8,
    capitalization        Nullable(BOOL),
    percent               Nullable(Float64),
    start_date             Nullable(String),
    end_date_offset         Nullable(Int32),
    end_date_offset_interval Nullable(String),
    payoff_step            Nullable(Int32),
    payoff_interval        Nullable(String)
) ENGINE = MergeTree PRIMARY KEY id;