name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Download and Install git-cliff
        run: |
          curl -L "https://github.com/orhun/git-cliff/releases/download/v2.2.1/git-cliff-2.2.1-x86_64-unknown-linux-gnu.tar.gz" -o git-cliff.tar.gz  # Скачивание git-cliff
          tar -xzf git-cliff.tar.gz  # Распаковка скачанного архива
          mv git-cliff-2.2.1/git-cliff /usr/local/bin/  # Перемещение исполняемого файла git-cliff в директорию /usr/local/bin

      - name: Generate Changelog
        run: git-cliff --config cliff.toml --output CHANGELOG.md

      - name: Commit Changelog
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add CHANGELOG.md
          git commit -m "Обновление CHANGELOG.md"
          git push https://github.com/${{ github.repository }}.git HEAD:main