name: PR Checks

on:
  pull_request:
    branches:
      - 'release/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Run tests
        run: go test ./...

      - name: Run linter
        run: go vet ./...